<div id="footer">

  <div id="footer-row1">
    Besucher:
    <img src="http://webcounter.goweb.de/4264"  alt="WEBCounter by GOWEB" valign="middle" height="11" width="44"/>
  </div>

  <div id="footer-row2">
    &copy; 2008 - 2011 -
    1. Duisburger Minigolf-Club 1962 e.V. -
    Heimanlage: Am Heidberg 20; Duisburg-Ungelsheim -
    <a href="mailto:info@duisburger-mc.de">info@duisburger-mc.de</a>
  </div>
</div>