    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Fusszeile -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <table border="0" cellpadding="0" cellspacing="0" width="800">
      <tbody>
        <tr>
          <td height="20" width="3">
            <img src="img/spacer/spacer.gif"  height="20" width="3">
          </td>
          <td background="img/title/bg_foot.jpg" height="20" width="795">
            <table class="foot" border="0" cellpadding="0" cellspacing="0"  width="100%">
              <tbody>
                <tr>
                  <td height="20" width="3">
                    <img src="img/spacer/spacer.gif"  height="1" width="3">
                  </td>
                  <td class="foot" align="left" height="20" width="300">
                    &nbsp;
                  </td>
                  <td class="foot" align="center" height="20" width="200">
                    &nbsp;
                  </td>
                  <td class="foot" align="right" height="20" width="280">
                    Besucher:
                    <img src="http://webcounter.goweb.de/4264"  alt="WEBCounter by GOWEB" valign="middle" height="11" width="44">
                  </td>
                  <td height="20" width="2">
                    <img src="img/spacer/spacer.gif" height="1" width="2">
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td height="20" width="2">
            <img src="img/spacer/spacer.gif"  height="20" width="2">
          </td>
        </tr>
        <tr>
          <td colspan="3" class="footnote" height="9">
            <table cellpadding="0" cellspacing="0" width="100%">
              <tbody>
                <tr>
                  <td class="footnote">
                    <img src="img/spacer/spacer.gif" height="9" width="1">
                  </td>
                  <td class="footnote" align="left">
                    &copy; 2008 - 2011 by Bobby Out
                    -
                    1. Duisburger Minigolf-Club 1962 e.V.
                    -
                    Heimanlage in Duisburg-Ungelsheim
                    -
                    <a href="mailto:webmaster@duisburger-mc.de">webmaster@duisburger-mc.de</a>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
