<div id="header">

  <div id="header-banner">
    <img id="header-title-img" src="/img/title/title.gif" />
  </div>

  <div id="header-mainmenu">
    <a href="/" class="mainmenu" title="Startseite">
      Startseite
    </a>
    <a href="/anlage.html" class="mainmenu" title="Heimanlage">
      Heimanlage
    </a>
    <a href="/sport/historie.html" class="mainmenu" title="Sport">
      Sport
    </a>
    <a href="/verein.html" class="mainmenu" title="Verein">
      Verein
    </a>
  </div>
               
  <div id="header-ticker">
    Aktuelles:
    <script language="JavaScript">
      insertPlaceHolder('InfoBox', 500, 15, 'left', '#ffffff', 0, '#0000ff');
    </script>
  </div>

  <img id="header-line" src="/img/6699ff.gif" />
  <img id="header-dmcball" src="/img/dmcball.gif" />
    
</div>