    <table border="0" cellpadding="0" cellspacing="0" width="800">
      <tbody>
        <tr>
          <td colspan="3" height="3">
            <img src="img/spacer/spacer.gif"  height="3" width="1">
          </td>
        </tr>
        <tr>
          <td height="60" width="3">
            <img src="img/spacer/spacer.gif"  height="60" width="3">
          </td>
          <td height="60" width="795">
            <table class="title" cellpadding="0" cellspacing="0" width="100%">
              <tbody>
                <tr>
                  <td background="img/title/bg_title.jpg" height="50"  width="795">
                    <img arc="img/spacer/spacer.gif" height="1" width="300">
                    <img src="img/title/title.gif" height="32" width="341">
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td height="60" width="2">
            <img src="img/spacer/spacer.gif" height="60" width="2">
          </td>
        </tr>
        <tr>
          <td colspan="3" height="2">
            <img src="img/spacer/spacer.gif" height="2" width="1">
          </td>
        </tr>
      </tbody>
    </table>

    <table border="0" cellpadding="0" cellspacing="0" width="800">
      <tbody>
        <tr>
          <td colspan="3" height="3">
            <img src="img/spacer/spacer.gif"  height="3" width="1">
          </td>
        </tr>
        <tr>
          <td height="20" width="3">
            <img src="img/spacer/spacer.gif"  height="20" width="3">
          </td>
          <td background="img/title/bg_menu.jpg" height="20" width="795" valign="middle">
            <a href="/main.php" target="main" class="mainmenu_actv" title="">
              <img src="img/diode1_actv2.gif" valign="middle" border="0" height="15" width="15">
              Home
            </a>
            <img src="img/mainmenu-tab.gif" height="15"  width="10">
            <a href="/sport/entwicklung.php" target="main" class="mainmenu" title="">
              <img src="img/diode1.gif" valign="middle"  border="0" height="15" width="15">
              Sport
            </a>
            <img src="img/mainmenu-tab.gif" height="15"  width="10">
            <a href="/club/wirueberuns.php" target="main"  class="mainmenu" title="">
              <img src="img/diode1.gif" valign="middle"  border="0" height="15" width="15">
              Verein
            </a>
            <img src="img/mainmenu-tab.gif" height="15"  width="10">
            <a href="/service/scores/" target="main"  class="mainmenu" title="">
              <img src="img/diode1.gif" valign="middle"  border="0" height="15" width="15">
              Service
            </a>
          </td>
          <td height="20" width="2">
            <img src="img/spacer/spacer.gif" height="20"  width="2">
          </td>
        </tr>
        <tr>
          <td colspan="3" height="2">
            <img src="img/spacer/spacer.gif"  height="2" width="1">
          </td>
        </tr>
      </tbody>
    </table>
    <!-- News-Ticker -->
    <table border="0" cellpadding="0" cellspacing="0" width="800">
      <tbody>
        <tr>
          <td height="20" width="5">
            <img src="img/spacer/spacer.gif"  height="20" width="5">
          </td>
          <td height="20" width="790">
            <table class="status" cellpadding="0" cellspacing="0" width="100%">
              <tbody>
                <tr>
                  <td class="caption_blue" height="20" valign="middle"  width="120">
                    Aktuelles:
                  </td>
                  <td height="20" valign="middle" width="740">
                    <script language="JavaScript">insertPlaceHolder('InfoBox', 500, 15, 'left', '#ffffff', 0, '#0000ff');</script>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td height="20" width="5">
            <img src="img/spacer/spacer.gif"  height="20" width="5">
          </td>
        </tr>
        <tr>
          <td colspan="3" height="5">
            <img src="img/spacer/spacer.gif"  height="5" width="5">
            <img src="img/6699ff.gif" height="1" width="790">
          </td>
        </tr>
      </tbody>
    </table>

    <div  style="position: absolute; top: 3px; left: 620px; width: 150px; height: 100px; z-index: 200;">
      <img  src="img/dmcball.gif">
    </div>