<div id="header">

  <div id="header-banner">
    <img id="header-title-img" src="img/title/title.gif" />
  </div>

  <div id="header-mainmenu">
    <a href="/" class="mainmenu_actv" title="Startseite">
      Startseite
    </a>
    <a href="/sport/" class="mainmenu" title="Sport">
      Sport
    </a>
    <a href="/verein/" class="mainmenu" title="Verein">
      Verein
    </a>
    <a href="/impressum.php" class="mainmenu" title="Impressum">
      Impressum
    </a>
  </div>
               
  <div id="header-ticker">
    Aktuelles:
    <script language="JavaScript">
      insertPlaceHolder('InfoBox', 500, 15, 'left', '#ffffff', 0, '#0000ff');
    </script>
  </div>

  <img id="header-line" src="img/6699ff.gif" />
  <img id="header-dmcball" src="img/dmcball.gif" />
    
</div>