<div id="leftcolumn">
  <div id="impressum">
    <strong>Impressum</strong>

    <p>
      1. Duisburger MC<br />
      Kärntener Str. 3<br />
      47249 Duisburg<br />
    </p>

    <strong>Vertreten durch:</strong>
    <p>
      Herr Dieter Meisters<br/>
      Herr Michael Meisters
    </p>
    
    <a href="/impressum.html">
      <img src="/img/arrow.gif"/>
      vollst. Impressum
    </a>
  </div>
</div>