<div id="leftcolumn">

  <div id="submenu">
    <a href="/sport/historie.html">
      <img src="/img/arrow.gif"/> Historie
    </a><br/>
    <a href="/sport/systeme.html">
      <img src="/img/arrow.gif"/> Systeme
    </a><br/>
    <a href="/sport/leistungssport.html">
      <img src="/img/arrow.gif"/> Leistungssport
    </a><br/>
    <a href="/sport/ausruestung.html">
      <img src="/img/arrow.gif"/> Ausrüstung
    </a><br/>
    <a href="/sport/technik.html">
      <img src="/img/arrow.gif"/> Technik &amp; Regeln
    </a><br/>
    <a href="/sport/vereine.html">
      <img src="/img/arrow.gif"/> Vereine &amp; Verbände
    </a><br/>
  </div>
  
  <div id="impressum">
    <strong>Impressum</strong>

    <p>
      1. Duisburger MC<br />
      Kärntener Str. 3<br />
      47249 Duisburg<br />
    </p>

    <strong>Vertreten durch:</strong>
    <p>
      Herr Dieter Meisters<br/>
      Herr Michael Meisters
    </p>
    
    <a href="/impressum.html">
      <img src="/img/arrow.gif"/>
      vollst. Impressum
    </a>
  </div>
</div>